Don't declare a Moshi property in a Gradle task
Otherwise attempting to update Moshi causes the build
to crash like this:

    org.gradle.api.GradleException: Could not load the value of field `factories`
      of `com.squareup.moshi.Moshi` bean found in field `moshi` of task `:cash-os:writeLockfile`
      of type `app.cash.better.dynamic.features.tasks.BaseLockfileWriterTask`.
            at org.gradle.internal.serialize.graph.BeanPropertyExtensionsKt.readPropertyValue(BeanPropertyExtensions.kt:70)
            at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldOf(BeanPropertyReader.kt:93)
            at org.gradle.internal.serialize.beans.services.BeanPropertyReader.readFieldsOf(BeanPropertyReader.kt:73)